resourceGroupName           =   "ACE-WINLAB-DEV"
primaryRegion               =   "North Central US"
secondaryRegion             =   "East US"
tertiaryRegion              =   "West US"
quaternaryRegion            =   "South Central US"
virtualNetworkName1         =   "ACE-WINLAB-VNET1"
virtualNetworkName2         =   "ACE-WINLAB-VNET2"
virtualNetworkName3         =   "ACE-WINLAB-VNET3"
virtualNetworkName4         =   "ACE-WINLAB-VNET4"
vnet1AddressSpace           =   ["192.168.1.0/24"]
vnet2AddressSpace           =   ["192.168.2.0/24"]
vnet3AddressSpace           =   ["192.168.3.0/24"]
vnet4AddressSpace           =   ["192.168.4.0/24"]
subnetName1                 =   "ACE-VM-SUBNET1"
subnetName2                 =   "ACE-VM-SUBNET2"
subnetName3                 =   "ACE-VM-SUBNET3"
subnetName4                 =   "ACE-VM-SUBNET4"
subnetAddressSpace1         =   "192.168.1.0/28"
subnetAddressSpace2         =   "192.168.2.0/28"
subnetAddressSpace3         =   "192.168.3.0/28"
subnetAddressSpace4         =   "192.168.4.0/28"
virtualMachineSize          =   "Standard_B2ms"
vmUserName                  =   "ACEUser"
vmPassword                  =   "Pa55w.rd1234!"